/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:17a93525-0212-412f-a5b0-bb94d97d925a",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_v9uDyU4GV",
    "aws_user_pools_web_client_id": "1tkfveo7oek1tqugs2ia6gibmj",
    "oauth": {}
};


export default awsmobile;
